### PR TITLE
Farscape default logger

### PR DESCRIPTION
**Pull request by HonoreDB**
Trivial logger injection.

### CODE REVIEW

**Comment by csavage-mdsol** [comment]
This looks good, but would a merge with a branch passing CI be reasonable at this point?

**Comment by HonoreDB** [comment]
Good idea.

**Comment by HonoreDB** [comment]
Merged in brave_new_develop, note that this required a one-line change in `http_client` since Faraday, when initialized with the block form, loses its default handling of hashes for request bodies.

**Comment by csavage-mdsol** [comment]
LGTM, merging

**Pull request merged**
