### PR TITLE
Furtherscape

### PR DESCRIPTION
**Pull request by sheavalentine-mdsol**
This is basic functionality allowing making requests that are unsafe or require a body such as DELETE, PUT, etc...

### CODE REVIEW

**Comment by HonoreDB** [comment]
Is this meant to target `brave_new_develop`?

**Comment by csavage-mdsol** [comment]
Yes

**Comment by sheavalentine-mdsol** [comment]
Is there a way to retarget it, or should I cancel this and open a new one?

**Comment by HonoreDB** [comment]
AFAIK you need to close this and open a new one.

**Pull request closed without merging**
